use_frameworks!

platform :ios, '8.0'

target 'PMReformerKeysKit_Example' do
  pod 'PMReformerKeysKit', :path => '../'

  target 'PMReformerKeysKit_Tests' do
    inherit! :search_paths

    
  end
end
